[package]
name = "aoc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.2.1"
cfg-if = "1.0.0"
itertools = "0.11.0"
nom = "7.1.3"

[features]
ex = []
dex = []

[[bin]]
name = "2201"
path = "bin/2022/01/bin.rs"

[[bin]]
name = "2202"
path = "bin/2022/02/bin.rs"

[[bin]]
name = "2203"
path = "bin/2022/03/bin.rs"

[[bin]]
name = "2204"
path = "bin/2022/04/bin.rs"

[[bin]]
name = "2205"
path = "bin/2022/05/bin.rs"

[[bin]]
name = "2206"
path = "bin/2022/06/bin.rs"

[[bin]]
name = "2207"
path = "bin/2022/07/bin.rs"

[[bin]]
name = "2208"
path = "bin/2022/08/bin.rs"

[[bin]]
name = "2209"
path = "bin/2022/09/bin.rs"

[[bin]]
name = "2210"
path = "bin/2022/10/bin.rs"

[[bin]]
name = "2211"
path = "bin/2022/11/bin.rs"
